apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-certificate
spec:
  dnsNames:
    - {{ .Values.expose.ingress.hosts.core }}
  secretName: {{ .Values.expose.tls.secret.secretName }}
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
