# secret root password
# apiVersion: v1
# kind: Secret
# metadata:
#   name: v17.3.1-gitlab-root-password
# data:
#   password: cGFzc3dvcmQ=

---
# minio pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: git-minio
spec:
  storageClassName: git-minio
  capacity:
    storage: 50Gi
  nfs:
    server: 192.168.31.238
    path: /share/gitlab/minio
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
# postgres pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: git-postgres
spec:
  storageClassName: git-postgres
  capacity:
    storage: 20Gi
  nfs:
    server: 192.168.31.238
    path: /share/gitlab/postgres
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
# redis pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: git-redis
spec:
  storageClassName: git-redis
  capacity:
    storage: 20Gi
  nfs:
    server: 192.168.31.238
    path: /share/gitlab/redis
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
# gitaly pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: git-gitaly
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: git-gitaly
  local:
    path: /share/gitlab/gitaly
  # TODO must fix
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kslave-1
# ---
# # kas  certification
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: kas-kgit-webpooyan-com-certificate
# spec:
#   dnsNames:
#     - kagent.kgit.webpooyan.com
#   secretName: kas-kgit-webpooyan-com-tls
#   issuerRef:
#     name: letsencrypt-prod
#     kind: ClusterIssuer
# ---
# # minio certification
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: minio-kgit-webpooyan-com-certificate
# spec:
#   dnsNames:
#     - io.kgit.webpooyan.com
#   secretName: minio-kgit-webpooyan-com-tls
#   issuerRef:
#     name: letsencrypt-prod
#     kind: ClusterIssuer

---
# web service certification
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-webservice-certificate
spec:
  dnsNames:
    - git.cluster.hyvatech.com
  secretName: gitlab-webservice-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
