services:
  dind-node-18:
    build:
      context: ./
      dockerfile: ./build_image.Dockerfile
      args:
        - IMAGE_REGISTRY=${IMAGE_REGISTRY}
        - BUILDKIT=1
      cache_from:
        - ${IMAGE_REGISTRY}/gitlab/docker:dind
        - type=local,src=./.docker-image/dind-node-18
      cache_to:
        - type=local,dest=./.docker-image/dind-node-18
        
    image: ${IMAGE_REGISTRY}/gitlab/docker:dind-node-18
