# secret root password
# apiVersion: v1
# kind: Secret
# metadata:
#   name: v17.3.1-gitlab-root-password
# data:
#   password: cGFzc3dvcmQ=

---
# minio pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-minio-nfs
spec:
  storageClassName: minio-nfs
  capacity:
    storage: 30Gi
  nfs:
    server: 192.168.31.238
    path: /var/gitlab-cluster/minio
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
# postgres pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-postgres-nfs
spec:
  storageClassName: postgres-nfs
  capacity:
    storage: 20Gi
  nfs:
    server: 192.168.31.238
    path: /var/gitlab-cluster/postgres
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
# redis pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-redis-nfs
spec:
  storageClassName: redis-nfs
  capacity:
    storage: 20Gi
  nfs:
    server: 192.168.31.238
    path: /var/gitlab-cluster/redis
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
# gitaly pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-gitaly-nfs
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gitaly-nfs
  local:
    path: /var/gitlab-cluster/gitaly
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kslave-1
---
# kas  certification
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kas-kgit-webpooyan-com-certificate
spec:
  dnsNames:
    - kagent.kgit.webpooyan.com
  secretName: kas-kgit-webpooyan-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
# minio certification
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-kgit-webpooyan-com-certificate
spec:
  dnsNames:
    - io.kgit.webpooyan.com
  secretName: minio-kgit-webpooyan-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

---
# web service certification
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-kgit-webpooyan-com-certificate
spec:
  dnsNames:
    - web.kgit.webpooyan.com
  secretName: gitlab-kgit-webpooyan-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
