apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kapp-dadras-certificate
  namespace: chabok
spec:
  dnsNames:
    - dadras.lawyerchabok.ir
  secretName: kapp-dadras-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
