{{- if ((.Values.config.operational_container_scanning).enabled) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gitlab-agent.ocs.clusterRoleBindingName" . }}
  labels:
    {{- include "gitlab-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "gitlab-agent.ocs.clusterRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "gitlab-agent.ocs.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | default "gitlab-agent" }}
{{- end }}

