{{- if ((.Values.config.operational_container_scanning).enabled) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gitlab-agent.fullname" . }}:ocs
  namespace: {{ .Release.Namespace | default "gitlab-agent" }}
  labels:
    {{- include "gitlab-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gitlab-agent.ocs.roleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "gitlab-agent.ocs.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | default "gitlab-agent" }}
{{- end }}

