{{- if ((.Values.config.operational_container_scanning).enabled) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gitlab-agent.ocs.roleName" . }}
  namespace: {{ .Release.Namespace | default "gitlab-agent" }}
  labels:
    {{- include "gitlab-agent.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
{{- end }}
