{{- if .Values.deployment.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "gitlab-zoekt.fullname" . }}-deployment-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab-zoekt.labels" . | nindent 4 }}
    {{- include "gitlab.standardLabels" . | nindent 4 }}
    {{- include "gitlab.commonLabels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.deployment.podDisruptionBudget.maxUnavailable | quote }}
  selector:
    matchLabels:
      {{- include "gitlab-zoekt.gatewaySelectorLabels" . | nindent 6 }}
{{- end }}
